http://localhost:3000/

###

get http://localhost:3000/api/users/

###

get http://localhost:3000/api/users/3

###

post http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Java",
  "lastName": "Script",
  "email": "is@email.com",
  "handle": "awesome",
  "password": "qwerty",
  "pic": "someurl"
}

###

delete http://localhost:3000/api/users/3

###

patch http://localhost:3000/api/users/3
Content-Type: application/json

{
  "firstName": "Coffee",
  "lastName": "Script"
}

###
post http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "simple@email.com",
  "password": "qwerty"
}

